---
abstract: 'Barebones CGI.'
author:
  - 'Bjoern Hee <github@spredehagl.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SPRAGL-Cgi_read
provides:
  SPRAGL::Cgi_read:
    file: lib/SPRAGL/Cgi_read.pm
    version: '0.71'
  SPRAGL::Cgi_read::Getchunk:
    file: lib/SPRAGL/Cgi_read/Getchunk.pm
requires:
  Encode: '0'
  List::Util: '0'
  Scalar::Util: '0'
resources:
  bugtracker: https://github.com/spragl/Cgi_read/issues
  license: http://apache.org/licenses/LICENSE-2.0
  repository: https://github.com/spragl/Cgi_read
version: '0.71'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
